

server:
  max-http-request-header-size: 64KB
  port: 8080
spring:
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
      enabled: true


  datasource:
    url: jdbc:postgresql://db:5432/quizapp
    username: postgres
    password: moein1379
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

  elasticsearch:
    uris: http://elastic:9200

  secret_key :
    "your-256-bit-secret-key-your-256-bit-secret-key"

  data:
    elasticsearch:
      repositories:
        enabled: true
    jdbc:
      dialect: postgresql

